#!/bin/sh

echo "Running aclocal"
aclocal -I m4 --install ||exit 1
echo "Running libtoolize"
which glibtoolize >/dev/null 2>&1 &&! which libtoolize >/dev/null 2>&1 &&LIBTOOLIZE_BIN=glibtoolize ||LIBTOOLIZE_BIN=libtoolize
$LIBTOOLIZE_BIN --copy --automake --install ||exit 1
# echo "Running autoheader"
# autoheader ||exit 1
echo "Running automake"
automake --foreign --add-missing --copy ||exit 1
echo "Running autoconf"
autoconf -f ||exit 1

echo "Now you are ready to run ./configure"
