name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure CXXFLAGS="-std=c++14 -O3 -g"
    - name: make
      run: make
    - name: make check
      run: make check

  build-MacOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: packages
      run: brew install automake libtool
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: MGTEST_RWLOCK_ITERATION_COUNT=50000; ./configure CPPFLAGS="-DMGTEST_RWLOCK_ITERATION_COUNT=$MGTEST_RWLOCK_ITERATION_COUNT" CXXFLAGS="-std=c++14 -O3 -g -DMGTEST_RWLOCK_ITERATION_COUNT=$MGTEST_RWLOCK_ITERATION_COUNT"
    - name: make
      run: make
    - name: make check
      run: make check
